### ISSUE TITLE
Paired T test minimal sample size?

### ISSUE THREAD

**Issue by Dysp** [estebanz01/ruby-statistics#20]
`sample1 = [1.0, 2.0, 3.0]`
`sample2 = [2.0, 3.0, 4.0]`
`StatisticalTest::TTest.paired_test(alpha = 0.05, :one_tail, sample1, sample2)`

`=> TypeError: nil can't be coerced into Fixnum`

`sample1 = [1.0, 2.0, 3.0, 4.0]`
`sample2 = [2.0, 3.0, 4.0, 3.0]`
`StatisticalTest::TTest.paired_test(alpha = 0.05, :one_tail, sample1, sample2)`

`=> {:probability=>0.1955011094781139, :p_value=>0.8044988905218862, :alpha=>0.05, :null=>true, :alternative=>false, :confidence_level=>0.95}`

It seems like the lowest sample size that can be used is 3. Is this intentional or am I missing something?

**Comment by estebanz01** [comment]
Interesting. I'll take a look. In the mean time, can you tell me which ruby version are you using with this?

**Comment by Dysp** [comment]
`ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux-gnu]`

**Comment by estebanz01** [comment]
@Dysp OK, the problem you are seeing is caused by a `t_score` of `-Infinity` and a standard deviation for the differences of zero.

If we follow the calculations made here: https://github.com/estebanz01/ruby-statistics/blob/master/lib/statistics/statistical_test/t_test.rb#L47-L52 we would see the following output:

```ruby
# Set the samples. Order matters.
irb(main):010:0> sample1 = [1.0, 2.0, 3.0]
=> [1.0, 2.0, 3.0]
irb(main):011:0> sample2 = [2.0, 3.0, 4.0]
=> [2.0, 3.0, 4.0]

# Calculate difference between samples
irb(main):012:0> differences = [sample1, sample2].transpose.map { |value| value.reduce(:-) }
=> [-1.0, -1.0, -1.0]

# Standard deviation
irb(main):014:0> differences.standard_deviation
=> 0.0
```
AFAIK, this is an edge case where we might need to re-evaluate the samples, although the gem should yell at you for that :grin:. I liked this answer for a question where std is zero https://stats.stackexchange.com/questions/78570/t-test-with-sample-standard-deviation-of-zero-possible .

Here's an example with samples of size 2:
```ruby
irb(main):001:0> sample1 = [5, 13]
=> [5, 13]
irb(main):002:0> sample2 = [12, 1]
=> [12, 1]
irb(main):003:0> StatisticalTest::TTest.paired_test(alpha = 0.05, :one_tail, sample1, sample2)
=> {:probability=>0.5819086824288511, :p_value=>0.4180913175711489, :alpha=>0.05, :null=>true, :alternative=>false, :confidence_level=>0.95}
```

I'll create a PR where the code checks the std to be greater than zero. Thanks for finding this!

**Comment by estebanz01** [comment]
I just add a basic first approach. You can take a look here: https://github.com/estebanz01/ruby-statistics/compare/issue-20

**Comment by estebanz01** [comment]
@Dysp I just released a new version where it raises an error when the gem encounters an std of zero when it's calculating the T tests. https://github.com/estebanz01/ruby-statistics/releases/tag/v2.0.2 You can update the gem as usual.
